package com.Capstone.Model;

        import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
        import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
        import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
        import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
        import io.swagger.models.auth.In;

@DynamoDBTable(tableName = "myOrders")
public class Order {

    private String id;
    private Integer userId;
    private String orderName;
    private String status;
    private Double unitPrice;
    private Integer quantity;
    private String category;
    public Order()
    {

    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getOrderName() {
        return orderName;
    }

    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    @DynamoDBAttribute
    public String getOrderStatus() {
        return status;
    }

    public void setOrderStatus(String status) {
        this.status = status;
    }
    @DynamoDBAttribute
    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @DynamoDBAttribute
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @DynamoDBAttribute
    public String getCategory() {return category;}

    public void setCategory(String category) {
        this.category = category;
    }
}